-- MySQL Script generated by MySQL Workbench
-- Sat Feb  7 23:22:59 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trade_turnover
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trade_turnover
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trade_turnover` DEFAULT CHARACTER SET utf8 ;
USE `trade_turnover` ;

-- -----------------------------------------------------
-- Table `trade_turnover`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trade_turnover`.`Suppliers` (
  `supplier_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(255) NOT NULL,
  `supplier_address` VARCHAR(255) NOT NULL,
  `supplier_phone` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`supplier_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trade_turnover`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trade_turnover`.`Products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(255) NOT NULL,
  `unit_of_measure` VARCHAR(50) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trade_turnover`.`GoodsReceipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trade_turnover`.`GoodsReceipt` (
  `receipt_id` INT NOT NULL AUTO_INCREMENT,
  `supplier_id` INT NULL,
  `product_id` INT NULL,
  `arrival_date` DATETIME NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`receipt_id`),
  INDEX `supplier_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `supplier`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `trade_turnover`.`Suppliers` (`supplier_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `product`
    FOREIGN KEY (`product_id`)
    REFERENCES `trade_turnover`.`Products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trade_turnover`.`Deals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trade_turnover`.`Deals` (
  `deal_id` INT NOT NULL AUTO_INCREMENT,
  `product_id` INT NULL,
  `deal_date` DATETIME NOT NULL,
  `count` INT NOT NULL,
  INDEX `product_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `product`
    FOREIGN KEY (`product_id`)
    REFERENCES `trade_turnover`.`Products` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
